"""update Assignment Submission model

Revision ID: 1879516ef4a3
Revises: 641a584ebcac
Create Date: 2023-11-29 02:05:49.619592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1879516ef4a3'
down_revision = '641a584ebcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
