"""create foreign key relation b/w Account and Assignment

Revision ID: 1c7657564fe4
Revises: 5a16f2c7fa4e
Create Date: 2023-10-05 18:18:03.890851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7657564fe4'
down_revision = '5a16f2c7fa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
