"""create Assignment Model

Revision ID: 5a16f2c7fa4e
Revises: 65093b2b79fd
Create Date: 2023-10-05 18:03:41.409466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a16f2c7fa4e'
down_revision = '65093b2b79fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('num_of_attempts', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('assignment_created', sa.DateTime(), nullable=False),
    sa.Column('assignment_updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('num_of_attempts>=1 AND num_of_attempts<=100', name='check_num_of_attempts'),
    sa.CheckConstraint('points>=1 AND points<=100', name='check_points'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('assignment')
    # ### end Alembic commands ###
