"""update Assignment Submission model

Revision ID: 6a9542c5e309
Revises: 1879516ef4a3
Create Date: 2023-11-29 02:49:29.274206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9542c5e309'
down_revision = '1879516ef4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
