name: Build and Share AMI

# on:
#   push:
#     branches:
#       - main
on: [pull_request]


jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run CI test
      run: |
        export FLASK_APP=app
        export FLASK_DEBUG=True
        export DATABASE_URL=${{ secrets.DATABASE_URL }}
        export CSV_PATH=./users.csv

        # Run the tests
        python -m unittest integration-test.py

    - name: Create webapp zip
      run: |
        zip -r webapp.zip . -x '*.git*' -x '.env' -x 'venv/*'
        
    - name: Upload webapp.zip
      uses: actions/upload-artifact@v2
      with:
        name: webapp.zip
        path: webapp.zip
      

  build-ami:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set environment variables for Packer
      run: |
        echo "PKR_VAR_aws_region=${{ vars.AWS_REGION }}" >> $GITHUB_ENV
        echo "PKR_VAR_source_ami=${{ vars.SOURCE_AMI }}" >> $GITHUB_ENV
        echo "PKR_VAR_ssh_username=${{ vars.SSH_USERNAME }}" >> $GITHUB_ENV
        echo "PKR_VAR_subnet_id=${{ vars.SUBNET_ID }}" >> $GITHUB_ENV
        echo "PKR_VAR_instance_type=${{ vars.INSTANCE_TYPE }}" >> $GITHUB_ENV
        echo "PKR_VAR_volume_size=${{ vars.VOLUME_SIZE }}" >> $GITHUB_ENV
        echo "PKR_VAR_volume_type=${{ vars.VOLUME_TYPE }}" >> $GITHUB_ENV
        echo "PKR_VAR_ami_users=${{ vars.AMI_USERS }}" >> $GITHUB_ENV
        echo "PKR_VAR_DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "PKR_VAR_FLASK_APP=${{ vars.FLASK_APP }}" >> $GITHUB_ENV
        echo "PKR_VAR_FLASK_DEBUG=${{ vars.FLASK_DEBUG }}" >> $GITHUB_ENV
        echo "PKR_VAR_DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "PKR_VAR_CSV_PATH=${{ vars.CSV_PATH }}" >> $GITHUB_ENV

    - name: Build AMI with Packer
      run: |
        packer init .
        packer build aws-debian.pkr.hcl
